const connectToDatabase = require('./db');

async function seedDatabase() {
  const db = await connectToDatabase();
  const carsCollection = db.collection('cars');

  const dummyCars = [
    {
        name: 'Tesla Model S',
        company: 'Tesla',
        driveType: '4 wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/tesla-model-s.jpg',
      },
      {
        name: 'McLaren 720S',
        company: 'McLaren',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 2,
        picture: 'https://example.com/mclaren-720s.jpg',
      },
      {
        name: 'Ferrari 488 GTB',
        company: 'Ferrari',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 2,
        picture: 'https://example.com/ferrari-488-gtb.jpg',
      },
      {
        name: 'Hyundai Sonata',
        company: 'Hyundai',
        driveType: 'front-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/hyundai-sonata.jpg',
      },
      {
        name: 'Toyota Camry',
        company: 'Toyota',
        driveType: 'front-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/toyota-camry.jpg',
      },{
        name: 'Toyota RAV4',
        company: 'Toyota',
        driveType: 'all-wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/toyota-rav4.jpg',
      },
      {
        name: 'Mercedes-Benz E-Class',
        company: 'Mercedes-Benz',
        driveType: 'rear-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/mercedes-benz-e-class.jpg',
      },
      {
        name: 'BMW M4',
        company: 'BMW',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 4,
        picture: 'https://example.com/bmw-m4.jpg',
      },
      {
        name: 'Audi Q5',
        company: 'Audi',
        driveType: 'all-wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/audi-q5.jpg',
      },
      {
        name: 'Lamborghini Huracan',
        company: 'Lamborghini',
        driveType: 'all-wheel drive',
        vehicleType: 'coupe',
        seats: 2,
        picture: 'https://example.com/lamborghini-huracan.jpg',
      },
      {
        name: 'Ford Mustang',
        company: 'Ford',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 4,
        picture: 'https://example.com/ford-mustang.jpg',
      },{
        name: 'Porsche 911',
        company: 'Porsche',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 4,
        picture: 'https://example.com/porsche-911.jpg',
      },
      {
        name: 'Chevrolet Corvette',
        company: 'Chevrolet',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 2,
        picture: 'https://example.com/chevrolet-corvette.jpg',
      },
      {
        name: 'Honda Civic',
        company: 'Honda',
        driveType: 'front-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/honda-civic.jpg',
      },
      {
        name: 'Nissan GT-R',
        company: 'Nissan',
        driveType: 'all-wheel drive',
        vehicleType: 'coupe',
        seats: 4,
        picture: 'https://example.com/nissan-gt-r.jpg',
      },
      {
        name: 'Volkswagen Golf',
        company: 'Volkswagen',
        driveType: 'front-wheel drive',
        vehicleType: 'hatchback',
        seats: 5,
        picture: 'https://example.com/volkswagen-golf.jpg',
      },
      {
        name: 'Jaguar F-PACE',
        company: 'Jaguar',
        driveType: 'all-wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/jaguar-f-pace.jpg',
      },
      {
        name: 'Lexus RX',
        company: 'Lexus',
        driveType: 'front-wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/lexus-rx.jpg',
      },
      {
        name: 'Maserati Ghibli',
        company: 'Maserati',
        driveType: 'rear-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/maserati-ghibli.jpg',
      },{
        name: 'Aston Martin DB11',
        company: 'Aston Martin',
        driveType: 'rear-wheel drive',
        vehicleType: 'coupe',
        seats: 4,
        picture: 'https://example.com/aston-martin-db11.jpg',
      },
      {
        name: 'Volvo XC90',
        company: 'Volvo',
        driveType: 'all-wheel drive',
        vehicleType: 'SUV',
        seats: 7,
        picture: 'https://example.com/volvo-xc90.jpg',
      },
      {
        name: 'Subaru Outback',
        company: 'Subaru',
        driveType: 'all-wheel drive',
        vehicleType: 'wagon',
        seats: 5,
        picture: 'https://example.com/subaru-outback.jpg',
      },
      {
        name: 'Kia Sorento',
        company: 'Kia',
        driveType: 'front-wheel drive',
        vehicleType: 'SUV',
        seats: 7,
        picture: 'https://example.com/kia-sorento.jpg',
      },
      {
        name: 'Mazda CX-5',
        company: 'Mazda',
        driveType: 'front-wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/mazda-cx-5.jpg',
      },
      {
        name: 'Jeep Wrangler',
        company: 'Jeep',
        driveType: '4 wheel drive',
        vehicleType: 'SUV',
        seats: 4,
        picture: 'https://example.com/jeep-wrangler.jpg',
      },
      {
        name: 'Land Rover Range Rover',
        company: 'Land Rover',
        driveType: '4 wheel drive',
        vehicleType: 'SUV',
        seats: 5,
        picture: 'https://example.com/land-rover-range-rover.jpg',
      },
      {
        name: 'Rolls-Royce Phantom',
        company: 'Rolls-Royce',
        driveType: 'rear-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/rolls-royce-phantom.jpg',
      },
      {
        name: 'Acura NSX',
        company: 'Acura',
        driveType: 'all-wheel drive',
        vehicleType: 'coupe',
        seats: 2,
        picture: 'https://example.com/acura-nsx.jpg',
      },
      {
        name: 'Infiniti Q50',
        company: 'Infiniti',
        driveType: 'rear-wheel drive',
        vehicleType: 'sedan',
        seats: 5,
        picture: 'https://example.com/infiniti-q50.jpg',
      },
  ];

  try {
    await carsCollection.insertMany(dummyCars);
    console.log('Dummy data added to the database');
  } catch (error) {
    console.error('Failed to add dummy data', error);
  }
}

seedDatabase();
